### PR TITLE
fix selection on textView bug in iOS 13

### PR DESCRIPTION
**Pull request by mohamed-aleem**
fix longTapGesture selection bug.

### CODE REVIEW

**Comment by guilhermedecampo** [comment]
hey @mohamed-aleem would be too much ask for a gif with the fix? 
We are busy and can't test right now.

**Comment by RossKinsella** [comment]
Here is a gif:
https://cl.ly/8cac2a95bb78

That PR appears to solve the issue for me

**Comment by guilhermedecampo** [comment]
amazing @RossKinsella, thank all!

**Comment by mohamed-aleem** [comment]
Sorry, didnt notice your message until recently. Glad it worked with you. And thanks. Keep it up :)

**Comment by jaroslawkrol** [comment]
Hey @mohamed-aleem 

I think the problem still occurs on IOS 13.5 on simulator and real device. Everything works correctly, except moving cursors to change highlighted text range. 
When i try to long-tap on cursor like on @RossKinsella 's gif, current highlighting dissapear and that's all. 

Tested on iPhone 7 IOS 13.5 and many simulators. 
On iOS 12 everything works fine.

**Comment by nsantacruz** [comment]
I'm also seeing that multi-word selection is not working on iOS 13.5. I can only select one word and when I try to drag the selector bars, it deselects. It is working fine on iOS 12.

**Comment by mohamed-aleem** [comment]
Thanks guys, will give it a look to see what needs to be done for the new ios.

**Comment by nsantacruz** [comment]
Thanks @mohamed-aleem. I'm going to create an issue to better track this and so that other users of this package understand this is a current issue.

**Pull request merged**
